#include "hediHelper/cuda/cusolverSP_error_check.h"
#include "hediHelper/cuda/cusparse_error_check.h"

const char *cusolverErrors[CUSOLVER_ERROR_SIZE]{
    "CUSOLVER_STATUS_SUCCESS",
    "CUSOLVER_STATUS_NOT_INITIALIZED",
    "CUSOLVER_STATUS_ALLOC_FAILED",
    "CUSOLVER_STATUS_INVALID_VALUE",
    "CUSOLVER_STATUS_ARCH_MISMATCH",
    "CUSOLVER_STATUS_MAPPING_ERROR",
    "CUSOLVER_STATUS_EXECUTION_FAILED",
    "CUSOLVER_STATUS_INTERNAL_ERROR",
    "CUSOLVER_STATUS_MATRIX_TYPE_NOT_SUPPORTED",
    "CUSOLVER_STATUS_NOT_SUPPORTED",
    "CUSOLVER_STATUS_ZERO_PIVOT",
    "CUSOLVER_STATUS_INVALID_LICENSE"};

const char *cusparseErrors[CUSPARSE_ERROR_SIZE]{
    "CUSPARSE_STATUS_SUCCESS",
    "CUSPARSE_STATUS_NOT_INITIALIZED",
    "CUSPARSE_STATUS_ALLOC_FAILED",
    "CUSPARSE_STATUS_INVALID_VALUE",
    " CUSPARSE_STATUS_ARCH_MISMATCH",
    "CUSPARSE_STATUS_MAPPING_ERROR",
    "CUSPARSE_STATUS_EXECUTION_FAILED",
    "CUSPARSE_STATUS_INTERNAL_ERROR",
    "CUSPARSE_STATUS_MATRIX_TYPE_NOT_SUPPORTED",
    "CUSPARSE_STATUS_ZERO_PIVOT"};